version: "3.8"

services:
    frontend:
        container_name: frontend
        build:
            context: frontend
            target: production
        ports:
            - 81:80
        restart: always