name: Deploy application to stands

on:
  push:
    branches:
      - main

jobs:
  download-source-code:
    runs-on: [self-hosted, backend]
    name: Download source code from repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
  
  push-to-dockerhub:
    name: Build and publish images to Docker Registry
    runs-on: backend
    needs: download-source-code
    env:
      frontend_rep: ${{ secrets.DOCKERHUB_USERNAME }}/hacks-ai-2023.frontend
      backend_rep: ${{ secrets.DOCKERHUB_USERNAME }}/hacks-ai-2023.backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{env.frontend_rep}}:latest
          platforms: linux/x86_64
      -
        name: Push backend image
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ${{env.backend_rep}}:latest
          platforms: linux/x86_64

  build-frontend:
    needs: push-to-dockerhub
    name: Pull frontend image
    runs-on: self-hosted
    steps:
      -
        name: Pull service
        run: docker compose pull
      -
        name: Build service
        run: docker compose -f docker-compose.frontend.yml up frontend -d --force-recreate
      -
        name: Check service
        run: docker ps -a

  build-backend:
    needs: push-to-dockerhub
    name: Pull backend image
    runs-on: backend
    steps:
      -
        name: Pull service
        run: docker compose pull
      -
        name: Build service
        run: docker compose -f docker-compose.backend.yml up frontend -d --force-recreate
      -
        name: Check service
        run: docker ps -a