name: Deploy application to stands

on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: [self-hosted, backend]
    name: init pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

  build-frontend:
    needs: init
    name: Build and publish frontend
    runs-on: self-hosted
    steps:
      -
        name: Stop service
        run: docker compose down
      -
        name: Build service
        run: docker compose -f docker-compose.frontend.yml up --build -d --force-recreate
      -
        name: Check service
        run: docker ps -a

  build-backend:
    needs: init
    name: Build and publish backend
    runs-on: backend
    steps:
      -
        name: Stop service
        run: docker compose down
      -
        name: Build service
        run: docker compose -f docker-compose.backend.yml up --build -d --force-recreate
      -
        name: Check service
        run: docker ps -a
